### ISSUE TITLE
Redundant and incorrect packaging

### ISSUE THREAD

**Issue by marco-eckstein** [mpetuska/npm-publish#76]
During build, npm-publish creates a package at `build/packages/js/`. At least for my small project, it contains almost the same set of files that the Kotlin multiplatform plugin already creates at `build/productionLibrary/`, given you have applied `binaries.library()` in the `js` configuration section. The only file that is different is `package.json`, and the one that npm-publish creates is actually missing fields that should be there, e.g. custom fields set in the `js` configuration section. I suppose this is also the cause of #65. The other files are exactly the same.

Why doesn't npm-publish simply publish `build/productionLibrary/`?

**Update (1)**

It appears that at least runtime `dependencies` are included correctly.

**Update (2)**

Apparently you can work around the problem by configuring:

```kotlin
packages {
    named("js") {
        packageJsonFile.set(file("build/productionLibrary/package.json"))
    }
}
```

**Comment by mpetuska** [comment]
The decision to have separate package.json was made due to historic reasons as well as avoid being tied to kotlin plugin so that npm-publish could be used without it. Additionally this allows for typesafe customisation of the file as well.

However missing transitive npm dependencies is a valid issue here and will need to be fixed.
